evdev_teleop_controller:
  ros__parameters:

    event: discovery_event   # Evdev path
    controller_name: logitech_panel # Name of controller, if discovery ignored

    publishers:
      button_subset: /teleop_cmd/button/
      axis_subset: /teleop_cmd/axis/

    services:
      is_init: /evdev_controller/is_init
      stop: /evdev_controller/stop